<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' your account could not be activated, please contact us!' => ' Ваш обліковий запис не можна активувати. Зв’яжіться з нами!',
    'A link to reset password will be sent to your email.' => 'Посилання на скидання пароля буде надіслано на вашу електронну пошту.',
    'About' => 'Про нас',
    'Account activation token cannot be blank.' => 'Маркер активації облікового запису не може бути порожнім.',
    'Address' => 'Адреса',
    'Are you sure you want to delete this item?' => 'Дійсно видалити цей елемент?',
    'Are you sure you want to delete this user?' => 'Дійсно видалити цього користувача',
    'Availability' => 'Наявність',
    'Back' => 'Назад',
    'Cancel' => 'Відмінити',
];
